name: Students Presubmit Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  BranchesQ:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: | 
          git clone https://github.com/${{ github.event.pull_request.head.repo.full_name }} tmprepo
      - name: test branches question
        run: |
          cd tmprepo
          git checkout main
          cd test
          bash branches.sh
      - name: test conflict question
        run: |
          cd tmprepo
          git checkout main
          cd test
          bash conflict.sh
      - name: test sensitive data question
        run: |
          cd tmprepo
          git checkout main
          bash test/sensitive_data.sh
      - name: test merge repos question
        run: |
          cd tmprepo
          git checkout main
          cd test
          bash merge_repos.sh
          
          
